/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 06-Feb-2022 22:54:13
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
// #include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * F:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */

const float numerator_sec1[3] = { 1, -2, 1 };	// b
const float denominator_sec1[3] = { 1, -1.993405819, 0.9934786558 }; // a
const float gain_sec1 = 0.9967210889f;

const float numerator_sec2[3] = { 1, -2, 1 }; // b
const float denominator_sec2[3] = { 1, -1.984255791, 0.9843283296 }; // a
const float gain_sec2 = 0.9921460152;
